Reservatios display
MarcoAurelioAntonio/Global-Academy-Client pull request #17
Opened 2023-06-13 19:41 UTC by MarcoAurelioAntonio

### Hi guys!, I hope are and be coding well!!

   #### - In this PR i have finish the card #8 for the project.

  - In this screen shot, you can see the route used, the render component, and the feched data from Server

2023-06-13 22:22 UTC, MarcoAurelioAntonio commented
After merge #18 PR, I solve al merge conflicts with `dev`

2023-06-14 12:54 UTC, kensteph requested changes
Hi @MarcoAurelioAntonio 👋!
You did a great job, the reservations displayed correctly. However, please consider these changes.

2023-06-14 12:54 UTC, kensteph commented on src/redux/displayreservationsSlice.js
> +);
As we already have a reservationsSlice, no need to create a new one (displayreservationsSlice). You can move this block to the reservationsSlice.

2023-06-14 12:54 UTC, kensteph commented on src/redux/displayreservationsSlice.js
> +  },
This block also.

2023-06-14 12:55 UTC, kensteph commented on src/redux/displayreservationsSlice.js
> +  },
After that, you can delete the displayreservationsSlice. Thank you

2023-06-14 13:49 UTC, MarcoAurelioAntonio commented on src/redux/displayreservationsSlice.js
> +  },
Hi @kensteph, ok good point 👍 , is better like you said. After I fixed, will tell you. Thanks!!

2023-06-14 14:54 UTC, merged